require: rubocop-rails
Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

BlockLength:
  Max: 70
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/SymbolArray:
  Enabled: false
